# Generated by Django 6.1 on 2026-08-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='account_profile',
        ),
    ]
